browser=chrome
baseUrl=https://pmo180.com:2017/Test-EN/CorePortal/
username=Automation-User1
password=Test@12345

strategyName=استراتيجية تقييم الجودة331
objectiveName=هدف..01-تجربة الاداء-331
kpiName=مؤشر..01.01- مؤشر تحربة الاداء-331

release=254
environment=Test-EN
tester=Sherif
system=TrackView